import { createPost } from "../infra/createPost";

export const setup = [
  createPost({
    title: "Macbook Pro 13 polegadas, processador M1, 16gb de RAM (Spacegray)",
    url: "https://amzn.to/3m10ee5",
    date: "2021-09-20",
    description: "Eu adorei a máquina, principalmente pela portabilidade e pela bateria que dura o dia todo. NADA a reclamar desse aqui.",
    source: "Setup",
    category: "workstation",
    tags: ["pc", "notebook", "setup", "apple", "afiliado"],
  }),
  createPost({
    title: "Magic Trackpad 3 (Branco)",
    url: "https://amzn.to/3kvgV0y",
    date: "2021-09-20",
    description: "Eu amo o trackpad do Macbook, mas quando eu preciso de mais espaço, eu uso esse aqui. É muito bom pra trabalhar com o Figma, por exemplo e meu pulso fica 0 bala no final de um dia de trabalho.",
    source: "Setup",
    category: "workstation",
    tags: ["trackpad", "mouse", "setup", "apple", "afiliado"],
  }),
  createPost({
    title: "Magic Keyboard com TouchID (Branco)",
    url: "https://amzn.to/3xO8oJm",
    date: "2021-09-20",
    description: "Eu usava um Keychron antes, mas derrubei água nele e acabei mudando pro magic trackpad. TER TOUCH ID NO TECLADO NÃO TEM PREÇO! (Na verdade tem, mas se pegar uma promoção boa ou comprar de fora até da pra pagar chorando menos).",
    source: "Setup",
    category: "workstation",
    tags: ["keyboard", "teclado", "setup", "apple", "afiliado"],
  }),
  createPost({
    title: "Streamdeck - Elgato",
    url: "https://amzn.to/3Zf3gtl",
    date: "2021-09-20",
    description: "Se você faz lives, ou gosta de ter atalhos, isso aqui é sensacional! 100% configurável e com uma interface bem simples de usar. Eu uso pra trocar de câmera, de microfone, de cenas, de música, de tudo!",
    source: "Setup",
    category: "workstation",
    tags: ["keyboard", "shortcuts", "setup", "elgato", "afiliado"],
  }),
  createPost({
    title: "Visual Studio Code",
    url: "https://code.visualstudio.com/",
    date: "2018-09-20",
    description: "Eu usava Sublime Text, até conhecer o VSCode e não larguei mais. Terminal integrado, autocomplete e o ecossistema de plugins me fez ficar aqui mesmo algumas vezes já tendo pego licença do WebStorm.",
    source: "Setup",
    category: "Development Tools",
    tags: [],
  }),
  createPost({
    title: "Figma",
    url: "https://www.figma.com/",
    date: "2021-09-20",
    description: "Hoje pra manter os challenges do canal entre outras coisas, eu uso o Figma. É muito bom pra prototipação e pra trabalhar em equipe (mesmo que eu tenha o plano com uma pessoa só).",
    source: "Setup",
    category: "Design",
    tags: ["design", "layout", "prototipação", "figma"],
  }),
  createPost({
    title: "CleanShot X",
    url: "https://cleanshot.com/",
    date: "2022-12-01",
    description: "Simplesmente o MELHOR software para tirar screenshots. Ele tem suporte para OCR, edição rápida, e um monte de outras coisas que eu não uso, mas que são muito úteis.",
    source: "Setup",
    category: "Produtividade",
    tags: [],
  })
];